osx_image: xcode9.3
language: objective-c
script:
- sudo gem install cocoapods -v 1.5.0
- travis_retry pod repo update > /dev/null
- pod lib lint --use-libraries --allow-warnings || pod lib lint --allow-warnings
